# Generated by Django 5.1.7 on 2025-03-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='security_deposit',
            field=models.FloatField(blank=True, help_text='Optional security deposit amount required from borrower', null=True),
        ),
    ]
