# Generated by Django 5.1.7 on 2025-03-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_current_role_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
