# Generated by Django 5.1.7 on 2025-03-27 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_profile_profile_pic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatattachment',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_role',
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='care_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='measurements',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='occasion_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='chatattachment',
            name='style_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('outfit_details', 'Outfit Details')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental_request', 'New Rental Request'), ('rental_approved', 'Rental Request Approved'), ('rental_declined', 'Rental Request Declined'), ('payment_received', 'Payment Received'), ('order_status', 'Order Status Update'), ('new_message', 'New Message'), ('chat_enabled', 'Chat Enabled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
