# Generated by Django 5.0.2 on 2025-03-27 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_chatmessage_options_alter_chatattachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcontract',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='verification/ids/'),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='verification/selfies/'),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('rental_approved', 'Rental Request Approved'), ('rental_declined', 'Rental Request Declined'), ('payment_received', 'Payment Received'), ('order_status', 'Order Status Update'), ('new_message', 'New Message'), ('chat_enabled', 'Chat Enabled'), ('contract_generated', 'Contract Generated'), ('contract_accepted', 'Contract Accepted')], max_length=50),
        ),
    ]
