# Generated by Django 5.0.2 on 2025-03-27 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_digitalcontract_id_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Chat Attachment', 'verbose_name_plural': 'Chat Attachments'},
        ),
        migrations.AlterModelOptions(
            name='digitalcontract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Digital Contract', 'verbose_name_plural': 'Digital Contracts'},
        ),
        migrations.AlterModelOptions(
            name='idverification',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'ID Verification', 'verbose_name_plural': 'ID Verifications'},
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='file',
            field=models.FileField(blank=True, help_text='Uploaded chat attachments', null=True, upload_to='documents/chat_attachments/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='digitalcontract',
            name='id_document',
            field=models.ImageField(blank=True, help_text='Clear photo of government-issued ID', null=True, upload_to='documents/verification/%Y/%m/ids/'),
        ),
        migrations.AlterField(
            model_name='digitalcontract',
            name='pdf_document',
            field=models.FileField(blank=True, help_text='PDF format only', null=True, upload_to='documents/contracts/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='digitalcontract',
            name='selfie_photo',
            field=models.ImageField(blank=True, help_text='Clear selfie with ID', null=True, upload_to='documents/verification/%Y/%m/selfies/'),
        ),
        migrations.AlterField(
            model_name='idverification',
            name='id_document',
            field=models.FileField(help_text='Upload a government-approved ID (JPEG, PNG, or PDF)', upload_to='documents/id_verification/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
    ]
