# Generated by Django 5.0.2 on 2025-03-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('verification_request', 'Verification Request'), ('verification_submitted', 'Verification Submitted'), ('contract_generated', 'Contract Generated'), ('contract_signed', 'Contract Signed')], default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
