# Generated by Django 5.0.2 on 2025-03-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_productview'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='id_document',
            field=models.ImageField(blank=True, help_text='Government ID document', null=True, upload_to='verifications/govt_id/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='selfie',
            field=models.ImageField(blank=True, help_text='Selfie photo', null=True, upload_to='verifications/selfie/'),
        ),
    ]
