# Generated by Django 5.0.2 on 2025-04-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_verificationrequest_id_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='metadata',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='acceptance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='lender_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/govt_id/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verifications/selfie/'),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='type',
            field=models.CharField(choices=[('govt_id', 'Government ID'), ('selfie', 'Selfie')], max_length=20),
        ),
    ]
