# Generated by Django 5.0.2 on 2025-04-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_verificationrequest_metadata_and_more'),
    ]

    operations = [
    ]
