# Generated by Django 5.0.2 on 2025-04-02 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20250402_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreLendingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pre_lending_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_lending_images', to='app.order')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
