# Generated by Django 5.0.2 on 2025-04-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_add_default_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
