# Generated by Django 5.0.2 on 2025-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_delete_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping',
        ),
        migrations.RemoveField(
            model_name='post',
            name='color',
        ),
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Good', 'Good'), ('Fair', 'Fair')], default='Good', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Self Pickup', 'Self Pickup'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Refunded', 'Refunded'), ('Refund Cancel', 'Refund Cancel')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='delivery_type',
            field=models.CharField(default='Self Pickup', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='rent_method',
            field=models.CharField(choices=[('Day', 'Per Day'), ('Week', 'Per Week'), ('Month', 'Per Month')], default='Day', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL'), ('7XL', '7XL'), ('8XL', '8XL'), ('9XL', '9XL'), ('10XL', '10XL'), ('Free Size', 'Free Size'), ('Custom Size', 'Custom Size')], default='M', max_length=20),
        ),
    ]
