# Generated by Django 5.0.2 on 2025-06-21 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_create_wishlist_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
