# Generated by Django 5.0.2 on 2025-06-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_wishlist_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Orange', 'Orange'), ('Brown', 'Brown'), ('Grey', 'Grey'), ('Multi', 'Multi-color')], default='Black', max_length=50),
        ),
    ]
