# Generated by Django 5.0.2 on 2025-12-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_add_color_field_to_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_fee',
        ),
        migrations.AddField(
            model_name='order',
            name='funds_released',
            field=models.BooleanField(default=False),
        ),
    ]
