# Generated by Django 5.0.2 on 2025-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_order_platform_fee_order_funds_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcontract',
            name='additional_terms',
            field=models.TextField(blank=True, help_text='Any additional terms or conditions', null=True),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='contract_security_deposit',
            field=models.FloatField(blank=True, help_text='Security deposit amount agreed in this contract', null=True),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='damage_penalties',
            field=models.TextField(blank=True, help_text='Description of damage penalties', null=True),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='late_fees',
            field=models.FloatField(blank=True, help_text='Late fee per day', null=True),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='rent_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='rent_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalcontract',
            name='rental_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
